In [5]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\igora\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


## Rank/Degree of Tensors
Number of dimensions involved in the Tensor

In [10]:
rank2_tensor = tf.Variable([['task','ok','um'],['test','yes','dois'],['aval','maybe','tres']], tf.string)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Shape of a Tensor
Amount of elements that exist in each dimension

In [11]:
tf.shape(rank2_tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3])>

## Changing Shape
The number of elements of a tensor is the product of the size of all its shapes. There are often many shapes that have the same number of elements, making it convenient to be able to change the shape of a tensor.

In [21]:
tensor1 = tf.ones([1,2,4]) # tensor with shape [1,2,4] full of ones
print(tensor1)

tensor2 = tf.reshape(tensor1, [2,2,2])
print(tensor2)

tensor3 = tf.reshape(tensor2, [4,-1]) # -1 gets a number to return a valid shape, 
print(tensor3)                        # with same product of last tensor


tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(1, 2, 4), dtype=float32)
tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]], shape=(4, 2), dtype=float32)


## Types of Tensors
- Variable
- Constant
- Placeholder
- SparseTensor

With the exception of **variable**, all of these tensors are immutable. We use the **variable** tensor to potentially change the value of a tensor posteriorly.

## Evaluating Tensors

Sometimes, it will be necessary to evaluate a tensor. That means get its value. Since tensors represent partially complete computation, there's something called *session* that can evaluate the tensor.

In [23]:
with tf.Session() as sess:
    tensor.eval()